
//예측 컬럼 추가

ALTER TABLE PUBLIC.MM_TAGS ADD ML_FORECAST_LEARNING_TAG_ID VARCHAR(100) ;
ALTER TABLE PUBLIC.MM_TAGS ADD ML_FORECAST_LEARNING_BEFORE_MINUTES VARCHAR(100) ;
ALTER TABLE PUBLIC.MM_TAGS ADD ML_FORECAST_TERM VARCHAR(100) ;
ALTER TABLE PUBLIC.MM_TAGS ADD ML_FORECAST_PREDICT_COUNT VARCHAR(100) ;
ALTER TABLE PUBLIC.MM_TAGS ADD ML_FORECAST_TIMESTAMP_FIT VARCHAR(100) ;
ALTER TABLE PUBLIC.MM_TAGS ADD USE_ML_FORECAST VARCHAR(1) ;


