package plantpulse.cep.db;

import java.sql.Connection;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * SchemeInitializer
 * 
 * @author lenovo
 * 
 */
public class SchemeInitializer {

	private static final Log log = LogFactory.getLog(SchemeInitializer.class);

	/**
	 * init
	 */
	public static void init() {

		ConnectionUtils utils = new ConnectionUtils();
		Connection connection = null;
		//
		try {
			connection = utils.getConnection();

			// user_login
			connection.prepareStatement("create table user_login (" + "user_id VARCHAR(50) PRIMARY KEY, " + "password VARCHAR(50)" + ");").execute();

			// MM_statement
			connection.prepareStatement("create table MM_statement (" + "statement_name VARCHAR(50) PRIMARY KEY, " + "statement_desc VARCHAR(1000)," + "epl VARCHAR(5000),"
					+ "listener VARCHAR(100)," + "is_pattern VARCHAR(1)," + "insert_date DATE," + "last_update_date DATE" + ");").execute();

			// alarm_seq
			connection.prepareStatement("create sequence alarm_seq as integer start with 1;").execute();

			// MM_alarm
			connection.prepareStatement("create table MM_alarm (" + "alarm_seq INTEGER GENERATED BY DEFAULT AS SEQUENCE ALARM_SEQ PRIMARY KEY, " + "priority VARCHAR(20)," + "alarm_date DATE,"
					+ "description VARCHAR(2000)," + "insert_date DATE" + ");").execute();

			/*
			 * connection.prepareStatement(
			 * "insert into user_login(user_id,password) values ('admin', 'admin');"
			 * ) .execute();
			 */

			log.info("DB Scheme initialized.");

		} catch (Exception ex) {
			log.error(ex);
		} finally {
			utils.closeConnection(connection);
		}
	}

}
